clc
clear all
close all

Wcon = [4.70	4.70	4.70	4.70	1.92	1.99	2.06	2.13	2.13	2.13	2.13	3.14	4.70	6.77	2.92	2.88	3.16];
Wdes = [26.46	22.49	19.33	16.40	12.56	11.77	11.00	10.37	7.08	4.93	3.15	4.98	7.35	11.80	6.44	5.56	4.77];

Eta_con = [0.2048	0.2048	0.2048	0.2048	0.1662	0.2249	0.2744	0.3250	0.3250	0.3250	0.3250	0.2587	0.2048	0.1707	0.2609	0.2594	0.2315];
Eta_des = [0.0364	0.0428	0.0498	0.0588	0.0254	0.0380	0.0514	0.0666	0.0976	0.1401	0.2191	0.1634	0.1311	0.0980	0.1185	0.1343	0.1533];

t_I = [26	26	26	26	26	26	26	26	26	26	26	26	26	26	26	26	26];
t_O = [34	34	34	34	25	28	31	34	34	34	34	34	34	34	34	34	34];

Omega_I = [10.5	10.5	10.5	10.5	14.5	14.5	14.5	14.5	14.5	14.5	14.5	12.5	10.5	8.5     12.5	12.5	12.5];
Omega_O = [20.5	18.5	16.5	14.5	14.5	14.5	14.5	14.5	12.5	10.5	8.5     8.5     8.5     8.5     12.5	12.5	12.5];



figure(1)
set(gcf,'Position',[360   200  680   420]);
% set(0,'defaultAxesFontSize',10)

h1 = bar([Wcon' Wdes'],'BarWidth',1,'EdgeColor','none');
set(h1, {'DisplayName'}, {'Condensing dehumidification','Desiccant wheel dehumidification'}');
colororder('default')
xticks(1:1:17);
xlabel('Case');
ylabel('Power [kW]');



yyaxis right;
h2 = plot(t_I,'s-','MarkerSize',5,'MarkerFaceColor',[0.9290 0.6940 0.1250]);
hold on
h3 = plot(t_O,'o-','MarkerSize',5,'MarkerFaceColor',[0.9290 0.6940 0.1250])
axis([0 18 5 36])
yticks(0:4:36);
ylabel('{\itt} [{\circ}C]');


h4 = plot((Omega_I-5)/(22-5)*(36-5)+5,'s-','Color',[0.4940 0.1840 0.5560],'MarkerSize',5,'MarkerFaceColor','w');
hold on
h5 = plot((Omega_O-5)/(22-5)*(36-5)+5,'o-','Color',[0.4940 0.1840 0.5560],'MarkerSize',5,'MarkerFaceColor','w')


ax = gca;
ax.YAxis(1).MinorTick = 'off';
ax.YAxis(2).MinorTick = 'on';
ax.YAxis(2).MinorTickValues = 2:2:36;
ax.XAxis.TickDirection = 'out';

lgd1= legend([h1],{'Condensing dehumidification','Desiccant wheel dehumidification','t_I','t_O','\omega_I','\omega_O'}, ... 
    'Location', 'southoutside','Orientation','horizontal','box','off');

hidden_ax = axes('Visible','off','NextPlot','add');
h2 = plot(t_I,'s-','Color',[0.9290 0.6940 0.1250],'MarkerFaceColor',[0.9290 0.6940 0.1250]);
h3 = plot(t_I,'o-','Color',[0.9290 0.6940 0.1250],'MarkerSize',4,'MarkerFaceColor',[0.9290 0.6940 0.1250])
h4 = plot(t_I,'s-','Color',[0.4940 0.1840 0.5560],'MarkerFaceColor','w');
h5 = plot(t_I,'o-','Color',[0.4940 0.1840 0.5560],'MarkerSize',5,'MarkerFaceColor','w')

[lgd2, objs] = legend([h2 h3 h4 h5],{'{\itt}_I','{\itt}_O','\omega_I','\omega_O'}, ... 
    'Location', 'southoutside','Orientation','horizontal','AutoUpdate','off','box','off');


delete(h2); delete(h3); delete(h4); delete(h5);


pos = ax.Position;
offset = 0.1;
% %Reduce width of the two axes generated by plotyy
pos(3) = pos(3) - 0.1;
set(ax,'position',pos);
%Determine the position of the third axes
pos(3) = pos(3) + 0.1;
ax2=axes('Position',pos,'box','off','Color',[0 0 0 0],'XColor',[0 0 0 0], ... 
    'YColor',[0.4940 0.1840 0.5560],'XTick',[],'YAxisLocation','right','Layer','bottom');
axis(([0 18 5 22]));
ylabel('\omega [g/kg]');

ax2.YAxis.MinorTick = 'on';
ax2.YAxis.MinorTickValues = 5:1:22;



linewidth = 2.5;
fontsize = 10;
markersize = 120;

% set(ax,'LineWidth',linewidth/2,'FontSize',fontsize);
% set(ax2,'LineWidth',linewidth/2,'FontSize',fontsize);

% 
% % lgd.Position = [ 0.1300    0.1016    0.6750    0.0460];
% lgd = legend(ax,[h1],{'Condensing dehumidification','Desiccant wheel dehumidification','t_I','t_O','\omega_I','\omega_O'}, ... 
%     'Location', 'southoutside','Orientation','horizontal');
% % lgd2 = legend([h1 h2 h3 h4 h5],{'Condensing dehumidification','Desiccant wheel dehumidification','ti','to','omegaI','omegaO'}, ... 
% %     'Location', 'southoutside','Orientation','horizontal');
% 
% lgd.NumColumns = 2;
% 
% legend(ax2,[h2 h3 h4 h5],{'t_I','t_O','\omega_I','\omega_O'}, ... 
%     'Location', 'southoutside','Orientation','horizontal','Color','w');
% 
% pos = ax.Position;
% offset = 0.1;
% % %Reduce width of the two axes generated by plotyy
% pos(3) = pos(3) - 0.1;
% set(ax2,'position',pos);

% lgd2.NumColumns = 2;
lgd2.Position([1 3]) = lgd1.Position([1 3]);
lgd2.Position(2) = lgd1.Position(2)-lgd2.Position(4);

